stages:
  - deploy

deploy:
  stage: deploy
  image: docker/compose
  tags:
    - mvbureev
  before_script:
    - cp $ENV_SENTRY_CI_FILE ./.env
    - source ./.env | true
    - cat ./.env
    - docker-compose ps
    - docker-compose version
    - docker info
  script:
    # - docker-compose run --rm sentry-base upgrade
    - docker-compose up -d
  only:
    - main
