stages:
  - deploy

variables:
  ENV_FILE: .env.local

deploy:
  stage: deploy
  image: docker/compose
  tags:
    - mvbureev
  before_script:
    - echo -e $ENV_SENTRY_CI_FILE > $ENV_FILE | true
    - source $ENV_FILE | true
    - docker-compose ps
    - docker info
    - docker-compose version
    - docker-compose config
  script:
    - docker-compose run --rm sentry-base upgrade
    - docker-compose up -d
  only:
    - main
