stages:
  - deploy

variables:
  ENV_FILE: .env

deploy:
  stage: deploy
  image: docker/compose
  tags:
    - mvbureev
  before_script:
    - echo -e $ENV_SENTRY_CI_FILE > $ENV_FILE | true
    - source $ENV_FILE | true
    - cat $ENV_FILE
    - docker-compose ps
    - docker info
    - docker-compose version
    - docker-compose --env-file $ENV_FILE config
  script:
    - docker-compose run --rm sentry-base upgrade
    - docker-compose up -d
  only:
    - main
